apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bookshop-java-subscriber
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: cap-kyma-2-0-n9uo22n1-bookshop-java-approuter-sidak
  service:
    name: bookshop-java-approuter
    port: 8080
  rules:
      - accessStrategies:
        - handler: allow
        methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
        path: /.*