{{- if .Values.networkSecurity.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "web-application.fullname" . }}
  labels: {{- include "web-application.labels" . | nindent 4 }}
spec:
  ingress:
{{- if .Values.expose.enabled }}
  - from:
    - podSelector:
        matchLabels:
          app: istio-ingressgateway
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
{{- end }}
{{- if .Values.networkSecurity.allowNamespaceInternal }}
  - from:
    - podSelector: {}
{{- end }}
{{- range $netRule := .Values.networkSecurity.ingress }}
  - from:
    -
    {{- if $netRule.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ tpl $netRule.namespace $ }}
    {{- end }}
    {{- if $netRule.podLabelsSelector }}
      podSelector:
        matchLabels: {{ tpl ($netRule.podLabelsSelector | toYaml) $ | nindent 10 }}
    {{- else }}
      podSelector: {}
    {{- end }}
{{- end }}
  policyTypes:
  - Ingress
  podSelector:
    matchLabels: {{- include "web-application.selectorLabels" . | nindent 6 }}
{{- end }}
